### ISSUE TITLE
java.lang.RuntimeException Caused by: java.io.IOException in Android 5.0 and 5.1

### ISSUE THREAD

**Issue by themanjsl** [AndreaCioccarelli/BillingProtector#2]
Hi. I'm getting this issue for android versions 5.0 and 5.1.
Wondering if there's anything I can do in order to prevent this issue.
Thanks in advance.

Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.myapp/com.myapp.ui.main.MainActivity}: java.io.IOException: Error running exec(). Command: [which, su] Working Directory: null Environment: null
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp/com.myapp.ui.main.MainActivity}: java.io.IOException: Error running exec(). Command: [which, su] Working Directory: null Environment: null
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2702)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
       at android.app.ActivityThread.access$900(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5951)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by java.io.IOException
Error running exec(). Command: [which, su] Working Directory: null Environment: null
Caused by java.io.IOException: Error running exec(). Command: [which, su] Working Directory: null Environment: null
       at java.lang.ProcessManager.exec(ProcessManager.java:211)
       at java.lang.Runtime.exec(Runtime.java:173)
       at java.lang.Runtime.exec(Runtime.java:246)
       at java.lang.Runtime.exec(Runtime.java:189)
       at com.andreacioccarelli.billingprotector.utils.RootUtils.extractPath$library_release(RootUtils.java:30)
       at com.andreacioccarelli.billingprotector.utils.RootUtils.hasRootAccess$library_release(RootUtils.java:60)
       at com.andreacioccarelli.billingprotector.BillingProtector.isRootInstalled(BillingProtector.java:22)
       at com.myapp.util.MyValidityChecker.checkIfDeviceIsRooted(MyValidityChecker.java:25)
       at com.myapp.util.MyValidityChecker.isUserRootedOrPirateAppsInstalled(MyValidityChecker.java:17)
       at com.myapp.ui.main.MainActivity.finishAppIfRootedOrPirateInstalled(MainActivity.java:823)
       at com.myapp.ui.main.MainActivity.onCreate(MainActivity.java:484)
       at android.app.Activity.performCreate(Activity.java:6289)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2655)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
       at android.app.ActivityThread.access$900(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5951)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by java.io.IOException
Permission denied
Caused by java.io.IOException: Permission denied
       at java.lang.ProcessManager.exec(ProcessManager.java)
       at java.lang.ProcessManager.exec(ProcessManager.java:209)
       at java.lang.Runtime.exec(Runtime.java:173)
       at java.lang.Runtime.exec(Runtime.java:246)
       at java.lang.Runtime.exec(Runtime.java:189)
       at com.andreacioccarelli.billingprotector.utils.RootUtils.extractPath$library_release(RootUtils.java:30)
       at com.andreacioccarelli.billingprotector.utils.RootUtils.hasRootAccess$library_release(RootUtils.java:60)
       at com.andreacioccarelli.billingprotector.BillingProtector.isRootInstalled(BillingProtector.java:22)
       at com.myapp.util.MyValidityChecker.checkIfDeviceIsRooted(MyValidityChecker.java:25)
       at com.myapp.util.MyValidityChecker.isUserRootedOrPirateAppsInstalled(MyValidityChecker.java:17)
       at com.myapp.ui.main.MainActivity.finishAppIfRootedOrPirateInstalled(MainActivity.java:823)
       at com.myapp.ui.main.MainActivity.onCreate(MainActivity.java:484)
       at android.app.Activity.performCreate(Activity.java:6289)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2655)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
       at android.app.ActivityThread.access$900(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5951)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by AndreaCioccarelli** [comment]
Hey, could you share some code where you instanciate and use Billing protector?
It looks like an error happening when root checking is performed.

**Comment by AndreaCioccarelli** [comment]
After further analysis, the root checking utility seems not to be not exhaustive while catching exceptions. Will look into that further.

**Comment by themanjsl** [comment]
Hi. Sorry for the late response.

The error occurs when running the following code.

<MainActivity.java>
private val bp = BillingProtector(context)

override fun onCreate(savedInstanceState: Bundle?) {
      super.onCreate(savedInstanceState)
      setContentView(R.layout.new_activity_main)

      checkIfUserIsValid()
}

// check if device is rooted or pirate apps are installed
private fun checkIfUserIsValid(){
      // check if user's device is rooted
      if(bp.isRootInstalled()){
            Timber.i("DEVICE IS ROOTED")
      }

      // check if user's device contains pirated apps
      val pirateAppList = bp.getPirateAppsList()
      if (pirateAppList.isNotEmpty()) {
         Timber.i("PIRATE APP INSTALLED")
       }
}
</MainActivity.java>


Interestingly, after changing the code so that checkIfUserIsValid() runs on
the background thread,
I haven't received errors for the past 12 hours.
